/**
 * @packageDocumentation
 * @module api.functional.oauth.google
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";

import type { AccountAPI } from "./../../../../interface/account/controller.interface";

/**
 * @controller SignInController.googlecb()
 * @path GET /oauth/google
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function googlecb
    (
        connection: IConnection
    ): Promise<googlecb.Output>
{
    return Fetcher.fetch
    (
        connection,
        googlecb.ENCRYPTED,
        googlecb.METHOD,
        googlecb.path()
    );
}
export namespace googlecb
{
    export type Output = AccountAPI.SignInResponse;

    export const METHOD = "GET" as const;
    export const PATH: string = "/oauth/google";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(): string
    {
        return `/oauth/google`;
    }
}