/**
 * @packageDocumentation
 * @module api.functional.oauth.google
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";

import type { IAuthUsecase } from "./../../../../interface/user/auth.usecase.interface";

/**
 * @controller AuthController.callbackFromGoogle()
 * @path GET /oauth/google
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function callbackFromGoogle
    (
        connection: IConnection
    ): Promise<callbackFromGoogle.Output>
{
    return Fetcher.fetch
    (
        connection,
        callbackFromGoogle.ENCRYPTED,
        callbackFromGoogle.METHOD,
        callbackFromGoogle.path()
    );
}
export namespace callbackFromGoogle
{
    export type Output = IAuthUsecase.SignInResponse;

    export const METHOD = "GET" as const;
    export const PATH: string = "/oauth/google";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(): string
    {
        return `/oauth/google`;
    }
}