/**
 * @packageDocumentation
 * @module api.functional.sign_in
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";

export * as google from "./google";
export * as github from "./github";

/**
 * 로그인 테스트용 api
 * 
 * @controller AuthController.signInTest()
 * @path GET /sign-in
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function signInTest
    (
        connection: IConnection
    ): Promise<void>
{
    return Fetcher.fetch
    (
        connection,
        signInTest.ENCRYPTED,
        signInTest.METHOD,
        signInTest.path()
    );
}
export namespace signInTest
{

    export const METHOD = "GET" as const;
    export const PATH: string = "/sign-in";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(): string
    {
        return `/sign-in`;
    }
}