/**
 * @packageDocumentation
 * @module api.functional.users
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";

import type { UserSchema } from "./../../interface/user/user.schema.interface";

/**
 * 사용자 프로필 조회 API
 * 
 * @tag user
 * 
 * @controller UsersController.getPulicProfile()
 * @path GET /users/:user_id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function getPulicProfile
    (
        connection: IConnection,
        id: string
    ): Promise<getPulicProfile.Output>
{
    return Fetcher.fetch
    (
        connection,
        getPulicProfile.ENCRYPTED,
        getPulicProfile.METHOD,
        getPulicProfile.path(id)
    );
}
export namespace getPulicProfile
{
    export type Output = UserSchema.Public;

    export const METHOD = "GET" as const;
    export const PATH: string = "/users/:user_id";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(id: string): string
    {
        return `/users/${encodeURIComponent(id)}`;
    }
}