/**
 * @packageDocumentation
 * @module api.functional.users
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";

import type { UserSchema } from "./../../interface/user/user.schema.interface";

/**
 * 사용자 프로필 조회 API
 * 
 * 활성화된 사용자의 정보만 조회합니다.
 * 
 * @tag user
 * @param connection connection Information of the remote HTTP(s) server with headers (+encryption password)
 * @param user_id 조회 대상의 id 입니다. uuid 타입만 허용합니다.
 * @returns 조회한 사용자의 공개 정보를 응답합니다.
 * @throw 400 Value of the URL parameter "user_id" is not a valid UUID.
 * @throw 404 일치하는 대상을 찾지 못했습니다.
 * 
 * @controller UsersController.getPulicProfile()
 * @path GET /users/:user_id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function getPulicProfile
    (
        connection: IConnection,
        id: string
    ): Promise<getPulicProfile.Output>
{
    return Fetcher.fetch
    (
        connection,
        getPulicProfile.ENCRYPTED,
        getPulicProfile.METHOD,
        getPulicProfile.path(id)
    );
}
export namespace getPulicProfile
{
    export type Output = UserSchema.Public;

    export const METHOD = "GET" as const;
    export const PATH: string = "/users/:user_id";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(id: string): string
    {
        return `/users/${encodeURIComponent(id)}`;
    }
}