/**
 * @packageDocumentation
 * @module api.functional.oauth.github
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";

import type { __object } from "./../../../../api/account/presentation/sign-in.controller";

/**
 * @controller SignInController.githubcb()
 * @path GET /oauth/github
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function githubcb
    (
        connection: IConnection
    ): Promise<githubcb.Output>
{
    return Fetcher.fetch
    (
        connection,
        githubcb.ENCRYPTED,
        githubcb.METHOD,
        githubcb.path()
    );
}
export namespace githubcb
{
    export type Output = __object;

    export const METHOD = "GET" as const;
    export const PATH: string = "/oauth/github";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(): string
    {
        return `/oauth/github`;
    }
}