/**
 * @packageDocumentation
 * @module api.functional.sign_in.github
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";
import typia from "typia";

import type { IAuthUsecase } from "./../../../interface/user/auth.usecase.interface";

/**
 * 로그인 API
 * 
 * 깃헙 oauth2 인증을 통해 얻은 code를 body를 통해 제공해야 합니다.
 * 
 * @tag authentication
 * 
 * @controller AuthController.signInGithub()
 * @path POST /sign-in/github
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function signInGithub
    (
        connection: IConnection,
        body: IAuthUsecase.SignInBody
    ): Promise<signInGithub.Output>
{
    return Fetcher.fetch
    (
        connection,
        signInGithub.ENCRYPTED,
        signInGithub.METHOD,
        signInGithub.path(),
        body,
        signInGithub.stringify
    );
}
export namespace signInGithub
{
    export type Input = IAuthUsecase.SignInBody;
    export type Output = IAuthUsecase.SignInResponse;

    export const METHOD = "POST" as const;
    export const PATH: string = "/sign-in/github";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(): string
    {
        return `/sign-in/github`;
    }
    export const stringify = (input: Input) => typia.assertStringify(input);
}