/**
 * @packageDocumentation
 * @module api.functional.sign_in.github
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";

/**
 * 깃헙 oauth 인증 API
 * 
 * 인증 성공시 로그인 세션을 생성하고 메인 페이지로 이동합니다.
 * 
 * 인증 실패시 로그인 실패 페이지로 이동합니다.
 * 
 * @tag authentication
 * 
 * @controller SignInController.signInByGithub()
 * @path GET /sign-in/github
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function signInByGithub
    (
        connection: IConnection
    ): Promise<void>
{
    return Fetcher.fetch
    (
        connection,
        signInByGithub.ENCRYPTED,
        signInByGithub.METHOD,
        signInByGithub.path()
    );
}
export namespace signInByGithub
{

    export const METHOD = "GET" as const;
    export const PATH: string = "/sign-in/github";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(): string
    {
        return `/sign-in/github`;
    }
}